const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL as string;

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: "#0f172a",
  viewportFit: "cover",
  colorScheme: "dark light",
  interactiveWidget: "resizes-content",
};

export const metadata = {
  title: "Bambang Harsono",
  description:
    "Full Stack Developer dan Creative Digital Solutions profesional dari Indonesia. Spesialis dalam pengembangan website modern, aplikasi web, UI/UX Design, dan solusi digital yang inovatif untuk bisnis.",
  authors: [{ name: "Rizki Ramadhan" }],
  creator: "Rizki Ramadhan",
  publisher: "Rizki Ramadhan",
  category: "Web Development & Digital Solutions",
  keywords: [
    "Digital Agency",
    "Web Development",
    "Web Design",
    "UI/UX Design",
    "Creative Agency",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Mobile App Development",
    "E-commerce Development",
    "SEO Optimization",
    "Digital Marketing",
    "Brand Identity",
    "Logo Design",
    "Graphic Design",
    "Indonesia Digital Agency",
    "Creative Solutions",
    "Modern Web Design",
    "Responsive Design",
    "Progressive Web App",
    "React Development",
    "Next.js Development",
    "Node.js Development",
    "Database Design",
    "API Development",
    "Cloud Solutions",
    "DevOps Services",
    "Pasar Kemis",
    "Kabupaten Tangerang",
    "Banten",
    "Tangerang",
    "Cikupa",
    "Curug",
    "Panongan",
    "Rajeg",
    "Sepatan",
    "Teluknaga",
    "Legok",
    "Karawaci",
    "Balaraja",
    "Tigaraksa",
    "Kosambi",
  ],
  icons: {
    icon: [
      {
        url: "/favicon.ico",
        sizes: "64x64 32x32 24x24 16x16",
        type: "image/x-icon",
      },
      {
        url: "/favicon.ico",
        sizes: "16x16",
        type: "image/png",
      },
      {
        url: "/favicon.ico",
        sizes: "32x32",
        type: "image/png",
      },
      {
        url: "/favicon.ico",
        sizes: "180x180",
        type: "image/png",
      },
      {
        url: "/favicon.ico",
        sizes: "192x192",
        type: "image/png",
      },
      {
        url: "/favicon.ico",
        sizes: "512x512",
        type: "image/png",
      },
    ],
    apple: "/favicon.ico",
    shortcut: "/favicon.ico",
    appleTouchIcon: "/favicon.ico",
  },
  tags: [
    {
      name: "Bambang Harsono",
      content: "Portofolio Bambang Harsono",
    },
    {
      name: "author",
      content: "Rizki Ramadhan",
    },
    {
      name: "robots",
      content: "index, follow",
    },
    {
      name: "language",
      content: "Indonesian, English",
    },
  ],
  manifest: "/manifest.json",
  metadataBase: new URL(BASE_URL),
  canonical: BASE_URL,
  other: {
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "format-detection": "telephone=no",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
    "msapplication-TileColor": "#0f172a",
    "application-name": "Bambang Harsono",
    "msapplication-tap-highlight": "no",
    "theme-color": "#0f172a",
    "msvalidate.01": `${process.env.NEXT_PUBLIC_BING_VERIFICATION}`,
    "google-site-verification": `${process.env.NEXT_PUBLIC_GOOGLE_SEARCH_CONSOLE_ID}`,
    "yandex-verification": `${process.env.NEXT_PUBLIC_YANDEX_VERIFICATION}`,
    "facebook-domain-verification": `${process.env.NEXT_PUBLIC_FACEBOOK_VERIFICATION}`,
    "pinterest-site-verification": `${process.env.NEXT_PUBLIC_PINTEREST_VERIFICATION}`,
  },
  openGraph: {
    type: "website",
    title: "Bambang Harsono",
    description:
      "Full Stack Developer dan Creative Digital Solutions profesional dari Indonesia. Spesialis dalam pengembangan website modern, aplikasi web, UI/UX Design, dan solusi digital yang inovatif untuk bisnis.",
    url: BASE_URL,
    siteName: "Bambang Harsono",
    locale: "id_ID",
    images: [
      {
        url: "/favicon.ico",
        width: 1200,
        height: 630,
        alt: "Bambang Harsono",
        type: "image/jpeg",
      },
      {
        url: "/favicon.ico",
        width: 600,
        height: 600,
        alt: "Bambang Harsono",
        type: "image/jpeg",
      },
      {
        url: "/favicon.ico",
        width: 800,
        height: 600,
        alt: "Bambang Harsono",
        type: "image/jpeg",
      },
    ],
    countryName: "Indonesia",
    emails: ["rr8027896@gmail.com"],
    phoneNumbers: ["+62-813-9863-2939"],
    streetAddress: "RG5J+6R6 Ps. Kemis, Kabupaten Tangerang, Banten",
    postalCode: "16640",
    locality: "Ps. Kemis",
    region: "Banten",
    country: "ID",
    profile: {
      firstName: "Bambang",
      lastName: "Harsono",
      username: "bambang_harsono",
      gender: "male",
    },
    article: {
      publishedTime: "2024-01-01T00:00:00+07:00",
      modifiedTime: new Date().toISOString(),
      section: "Web Development & Digital Solutions",
      tags: [
        "Full Stack Developer",
        "Web Development",
        "Creative Design",
        "Technology",
      ],
    },
    video: {
      url: "https://www.youtube.com/watch?v=uURhi3S5qEM",
      type: "video/mp4",
      width: 1280,
      height: 720,
    },
    audio: {
      url: `${BASE_URL}/audio-preview.mp3`,
      type: "audio/mpeg",
    },
    // New fields
    business: {
      name: "Bambang Harsono",
      type: "Full Stack Developer",
      category: "Technology",
      founded: "2024",
      employees: "1-10",
      revenue: "100K-1M",
    },
    organization: {
      name: "Bambang Harsono",
      url: BASE_URL,
      logo: `${BASE_URL}/favicon.ico`,
      sameAs: [
        "https://www.facebook.com/rizki.ramadhan.419859",
        "https://github.com/Rizkiramadhan20",
        "https://www.instagram.com/rzkir.20",
        "https://www.tiktok.com/@rzkir.20",
        "https://www.linkedin.com/in/rizki-ramadhan12",
        "https://www.youtube.com/@codingwithrizki",
      ],
    },
  },
  twitter: {
    card: "summary_large_image",
    title: "Bambang Harsono",
    description:
      "Full Stack Developer dan Creative Digital Solutions profesional dari Indonesia. Spesialis dalam pengembangan website modern, aplikasi web, UI/UX Design, dan solusi digital yang inovatif untuk bisnis.",
    creator: "@codingwithrizki",
    site: "@codingwithrizki",
    images: ["/twitter-image-main.jpg", "/twitter-image-square.jpg"],
    // New Twitter fields
    app: {
      name: "Bambang Harsono",
      id: {
        iphone: "bambang-harsono-app",
        ipad: "bambang-harsono-app",
        googleplay: "com.bambangharsono.app",
      },
      url: {
        iphone: "https://apps.apple.com/app/bambang-harsono",
        ipad: "https://apps.apple.com/app/bambang-harsono",
        googleplay:
          "https://play.google.com/store/apps/details?id=com.bambangharsono.app",
      },
    },
  },
  // New social media metadata
  facebook: {
    appId: process.env.NEXT_PUBLIC_FACEBOOK_APP_ID,
    pages: ["bambang-harsono"],
    admins: ["bambang-harsono"],
  },
  instagram: {
    username: "bambang_harsono",
    site: "https://www.instagram.com/bambang_harsono",
  },
  linkedin: {
    company: "bambang-harsono",
    site: "https://www.linkedin.com/in/bambang-harsono",
  },
  youtube: {
    channel: "UC-codingwithrizki",
    site: "https://www.youtube.com/@codingwithrizki",
  },
  tiktok: {
    username: "bambang_harsono",
    site: "https://www.tiktok.com/@bambang_harsono",
  },
  github: {
    username: "bambang_harsono",
    site: "https://github.com/bambang_harsono",
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SEARCH_CONSOLE_ID,
    googleTagManager: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID,
    yandex: process.env.NEXT_PUBLIC_YANDEX_VERIFICATION,
    bing: process.env.NEXT_PUBLIC_BING_VERIFICATION,
    facebook: process.env.NEXT_PUBLIC_FACEBOOK_VERIFICATION,
    pinterest: process.env.NEXT_PUBLIC_PINTEREST_VERIFICATION,
    // New verification codes
    alexa: process.env.NEXT_PUBLIC_ALEXA_VERIFICATION,
    yahoo: process.env.NEXT_PUBLIC_YAHOO_VERIFICATION,
    wot: process.env.NEXT_PUBLIC_WOT_VERIFICATION,
    norton: process.env.NEXT_PUBLIC_NORTON_VERIFICATION,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
    // New robots fields
    bingbot: {
      index: true,
      follow: true,
      "max-snippet": -1,
    },
    yandex: {
      index: true,
      follow: true,
    },
  },
  alternates: {
    canonical: BASE_URL,
    languages: {
      "id-ID": BASE_URL,
      "en-US": `${BASE_URL}/en`,
    },
  },
  // New structured data
  structuredData: {
    organization: {
      "@context": "https://schema.org",
      "@type": "Organization",
      name: "Bambang Harsono",
      url: BASE_URL,
      logo: `${BASE_URL}/favicon.ico`,
      description:
        "Full Stack Developer dan Creative Digital Solutions profesional dari Indonesia",
      address: {
        "@type": "PostalAddress",
        streetAddress: "RG5J+6R6 Ps. Kemis, Kabupaten Tangerang, Banten",
        addressLocality: "Ps. Kemis",
        addressRegion: "Banten",
        postalCode: "16640",
        addressCountry: "ID",
      },
      contactPoint: {
        "@type": "ContactPoint",
        telephone: "+62-813-9863-2939",
        contactType: "customer service",
        email: "rr8027896@email.com",
      },
      sameAs: [
        "https://www.facebook.com/bambang_harsono",
        "https://github.com/bambang_harsono",
        "https://www.instagram.com/bambang_harsono",
        "https://www.tiktok.com/@bambang_harsono",
        "https://www.linkedin.com/in/bambang_harsono",
        "https://www.youtube.com/@bambang_harsono",
      ],
    },
    website: {
      "@context": "https://schema.org",
      "@type": "WebSite",
      name: "Bambang Harsono",
      url: BASE_URL,
      description: "Full Stack Developer & Creative Digital Solutions",
      publisher: {
        "@type": "Organization",
        name: "Bambang Harsono",
      },
    },
    localBusiness: {
      "@context": "https://schema.org",
      "@type": "LocalBusiness",
      name: "Bambang Harsono",
      description: "Full Stack Developer & Creative Digital Solutions",
      url: BASE_URL,
      telephone: "+62-813-9863-2939",
      email: "rr8027896@email.com",
      address: {
        "@type": "PostalAddress",
        streetAddress: "RG5J+6R6 Ps. Kemis, Kabupaten Tangerang, Banten",
        addressLocality: "Ps. Kemis",
        addressRegion: "Banten",
        postalCode: "16640",
        addressCountry: "ID",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: "-6.5614",
        longitude: "106.6322",
      },
      openingHours: "Mo-Fr 09:00-18:00",
      priceRange: "$$",
    },
  },
  // New performance and security headers
  headers: {
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
    "X-DNS-Prefetch-Control": "on",
    "X-XSS-Protection": "1; mode=block",
  },
  // New analytics and tracking
  analytics: {
    googleAnalytics: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
    googleTagManager: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID,
    facebookPixel: process.env.NEXT_PUBLIC_FACEBOOK_PIXEL_ID,
    hotjar: process.env.NEXT_PUBLIC_HOTJAR_ID,
    mixpanel: process.env.NEXT_PUBLIC_MIXPANEL_TOKEN,
    amplitude: process.env.NEXT_PUBLIC_AMPLITUDE_API_KEY,
    segment: process.env.NEXT_PUBLIC_SEGMENT_WRITE_KEY,
  },
};

export default metadata;
